template: DAF
api_key: 5iYCK2lApzMxUuVM3qFtq0OzBORwGpjfR9K
parent: Patients
config:
  notes: DAF Datasources
  data-sources:
    - postgres:
        notes: Postgres Replica
        replica: Default
        source: postgres
        start-order: 1
        ami: ami-0dfffed98347ecd
connectors:
  - postgres:
      file: /src/main/resources/application.properties
      jdbc: spring.datasource.url
      host: spring.database.url
      database: spring.database.database
      port: spring.database.port
      username: spring.datasource.username
      password: spring.datasource.password
environments:
  - prep1:
      branch: prep1
      datapod: prep1
      when:
        - push: datapod.refresh
  - prep2:
      branch: prep2
      datapod: prep2
      when:
        - push: datapod.refresh
  - prep3:
      branch: prep3
      datapod: prep3
      when:
        - push: datapod.refresh
  - prep4:
      branch: prep4
      datapod: prep4
      when:
        - push: datapod.refresh
  - prep5:
      branch: prep5
      datapod: prep5
      when:
        - push: datapod.refresh
  - prep6:
      branch: prep6
      datapod: prep6
      when:
        - push: datapod.refresh
  - prep7:
      branch: prep7
      datapod: prep7
      when:
        - push: datapod.refresh