---
  - name: All the tools playbook
    hosts: all
    become: yes
    pre_tasks:
      - name: ca-certificates update command line execution
        command: /bin/update-ca-trust
    vars:
      java_packages:
        - java-11-openjdk
      jenkins_plugins: # have to list all dependencies due to https://github.com/ansible/ansible/issues/24864
        - {name: blueocean, version: '1.19.0'}
        - {name: trilead-api, version: '1.0.5'}
        - {name: jaxb, version: '2.3.0.1'}
        - {name: jdk-tool, version: '1.3'}
        - {name: structs, version: '1.20'}
        - {name: scm-api, version: '2.6.3'}
        - {name: blueocean-commons, version: '1.19.0'}
        - {name: script-security, version: '1.66'}
        - {name: blueocean-rest, version: '1.19.0'}
        - {name: workflow-step-api, version: '2.20'}
        - {name: workflow-api, version: '2.37'}
        - {name: github-api, version: '1.95'}
        - {name: workflow-support, version: '3.3'}
        - {name: token-macro, version: '2.10'}
        - {name: command-launcher, version: '1.3'}
        - {name: github, version: '1.29.5'}
        - {name: bouncycastle-api, version: '2.17'}
        - {name: delphix, version: '2.0.4'}
        - {name: credentials, version: '2.3.0'}
        - {name: pipeline-model-extensions, version: '1.3.9'}
        - {name: apache-httpcomponents-client-4-api, version: '4.5.10-2.0'}
        - {name: jenkins-design-language, version: '1.19.0'}
        - {name: ssh-credentials, version: '1.18'}
        - {name: jsch, version: '0.1.55.1'}
        - {name: git-client, version: '2.9.0'}
        - {name: git-server, version: '1.8'}
        - {name: blueocean-core-js, version: '1.19.0'}
        - {name: plain-credentials, version: '1.5'}
        - {name: github-branch-source, version: '2.5.8'}
        - {name: credentials-binding, version: '1.20'}
        - {name: jackson2-api, version: '2.10.0'}
        - {name: variant, version: '1.3'}
        - {name: aws-java-sdk, version: '1.11.650'}
        - {name: pubsub-light, version: '1.13'}
        - {name: aws-credentials, version: '1.28'}
        - {name: durable-task, version: '1.30'}
        - {name: authentication-tokens, version: '1.3'}
        - {name: workflow-durable-task-step, version: '2.34'}
        - {name: htmlpublisher, version: '1.21'}
        - {name: display-url-api, version: '2.3.2'}
        - {name: mailer, version: '1.29'}
        - {name: blueocean-web, version: '1.19.0'}
        - {name: workflow-basic-steps, version: '2.18'}
        - {name: blueocean-jwt, version: '1.19.0'}
        - {name: purge-job-history, version: '1.3'}
        - {name: ace-editor, version: '1.1'}
        - {name: favorite, version: '2.3.2'}
        - {name: jquery-detached, version: '1.2.1'}
        - {name: blueocean-rest-impl, version: '1.19.0'}
        - {name: workflow-scm-step, version: '2.9'}
        - {name: workflow-cps, version: '2.74'}
        - {name: blueocean-git-pipeline, version: '1.19.0'}
        - {name: cloudbees-folder, version: '6.9'}
        - {name: docker-commons, version: '1.15'}
        - {name: workflow-cps-global-lib, version: '2.15'}
        - {name: branch-api, version: '2.5.4'}
        - {name: workflow-job, version: '2.35'}
        - {name: blueocean-config, version: '1.19.0'}
        - {name: workflow-multibranch, version: '2.21'}
        - {name: docker-workflow, version: '1.21'}
        - {name: pipeline-milestone-step, version: '1.3.1'}
        - {name: mercurial, version: '2.8'}
        - {name: pipeline-input-step, version: '2.11'}
        - {name: blueocean-dashboard, version: '1.19.0'}
        - {name: pipeline-stage-step, version: '2.3'}
        - {name: pipeline-stage-tags-metadata, version: '1.3.9'}
        - {name: pipeline-graph-analysis, version: '1.10'}
        - {name: jira, version: '3.0.10'}
        - {name: pipeline-rest-api, version: '2.12'}
        - {name: handlebars, version: '1.1.1'}
        - {name: momentjs, version: '1.1.1'}
        - {name: blueocean-jira, version: '1.19.0'}
        - {name: pipeline-stage-view, version: '2.12'}
        - {name: blueocean-display-url, version: '2.3.0'}
        - {name: pipeline-build-step, version: '2.9'}
        - {name: sse-gateway, version: '1.20'}
        - {name: pipeline-model-api, version: '1.3.9'}
        - {name: pipeline-model-declarative-agent, version: '1.1.1'}
        - {name: git, version: '3.12.1'}
        - {name: pipeline-model-definition, version: '1.3.9'}
        - {name: junit, version: '1.28'}
        - {name: blueocean-events, version: '1.19.0'}
        - {name: matrix-project, version: '1.14'}
        - {name: blueocean-i18n, version: '1.19.0'}
        - {name: lockable-resources, version: '2.6'}
        - {name: blueocean-autofavorite, version: '1.2.4'}
        - {name: workflow-aggregator, version: '2.6'}
        - {name: blueocean-pipeline-scm-api, version: '1.19.0'}
        - {name: blueocean-pipeline-api-impl, version: '1.19.0'}
        - {name: blueocean-github-pipeline, version: '1.19.0'}
        - {name: handy-uri-templates-2-api, version: '2.1.8-1.0'}
        - {name: cloudbees-bitbucket-branch-source, version: '2.5.0'}
        - {name: blueocean-bitbucket-pipeline, version: '1.19.0'}
        - {name: blueocean-personalization, version: '1.19.0'}
        - {name: blueocean-pipeline-editor, version: '1.19.0'}
        - {name: blueocean-executor-info, version: '1.19.0'}
      jenkins_java_options: '-Djenkins.install.runSetupWizard=false -Dhudson.model.DirectoryBrowserSupport.CSP=\"script-src ''unsafe-inline'';\"'
      git_packages:
        - git
      nodejs_version: "10.x"
      nodejs_npm_global_packages:
        - '@angular/cli'
        - '@angular-devkit/build-angular'
    roles:
      - role: geerlingguy.java
      - role: geerlingguy.jenkins
      - role: geerlingguy.docker
      - role: geerlingguy.git
      - role: geerlingguy.nodejs
      - role: ocha.yarn
