---
- name: Postgres playbook
  hosts: all
  vars:
    ddp_password: "{{ lookup('env','DELPHIX_ADMIN_PASSWORD') }}"
    postgresql_port: 5432
    postgresql_version: "11.0"
    postgresql_packages:
      - postgresql11
      - postgresql11-server
      - postgresql11-contrib
      - postgresql11-libs
    postgresql_hba_entries:
      - { type: local, database: all, user: all, auth_method: peer }
      - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: trust }
      - { type: host, database: all, user: all, address: '::1/128', auth_method: md5 }
      - { type: host, database: all, user: all, address: '10.0.0.0/16', auth_method: trust }
      - { type: host, database: replication, user: delphixdb, address: '10.0.0.0/16', auth_method: trust }
    postgresql_global_config_options:
      - option: unix_socket_directories
        value: '{{ postgresql_unix_socket_directories | join(",") }}'
      - option: port
        value: "{{ postgresql_port }}"
      - option: listen_addresses
        value: "*"
      - option: wal_level
        value: archive
      - option: archive_mode
        value: "on"
      - option: archive_command
        value: "cp %p {{ postgresql_data_dir }}/../backups/%f"
      - option: archive_timeout
        value: "60"
      - option: max_wal_senders
        value: "2"
      - option: wal_keep_segments
        value: "10"
    postgresql_bin_path: "/usr/pgsql-11/bin"
    postgresql_data_dir: "/var/lib/pgsql/11/data"
    postgresql_config_path: "{{ postgresql_data_dir }}"
    postgresql_daemon: "postgresql-11"
    #Targets do not need postgres service to run
    postgresql_service_enabled: false
    delphix_user: postgres
    delphix_group: postgres
    delphix_home: /var/lib/pgsql
    delphix_toolkit: "{{ delphix_home }}/toolkit"
    toolkit_dir: "{{ delphix_toolkit }}"
    delphix_mount: "{{ delphix_home }}/mnt"
    delphix_ssh_keys:
    user_comment: 'PostgreSQL Server'
  roles:
    - role: geerlingguy.postgresql
      become: yes
    - role: delphix.target-host
      become: yes
    - role: delphix.self-enroll
      version: v0.3
  post_tasks:
    # https://jira.delphix.com/browse/DLPX-62018
    - name: Remove quotes from port number
      lineinfile:
        path: "{{ postgresql_config_path }}/postgresql.conf"
        regexp: '^port ='
        line: "port = {{ postgresql_port }}"
      become: true
    # https://docs.delphix.com/docs/delphix-administration/postgresql-environments-and-data-sources/postgresql-support-and-requirements/requirements-for-postgresql-target-hosts-and-databases
    - name: Add DELPHIX_PG_PATH for non-interactive logins
      lineinfile:
        path: "/etc/environment"
        regexp: '^DELPHIX_PG_PATH='
        line: "DELPHIX_PG_PATH={{ postgresql_bin_path }}:{{ postgresql_data_dir }}"
      become: true