---

- name: add the postgresql repo
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present

- name: "add {{ postgresql_package }}"
  yum:
    name: "{{ postgresql_package }}"
    state: present